### PR TITLE
Improve Linux make system, pull in OculusSDK from jherico/OculusSDK as a git submodule rather than tracking it ourselves

### PR DESCRIPTION
**Pull request by feilen**
With this, it pulls the latest 0.4.3 SDK from jherico's github and uses that instead. Additionally, it compiles all modules with '-O2' and some advantageous linker flags. It's still got the same segfault I was having before (and if someone could test if that happens on Windows without a rift that'd be grand) but this should make setting it up for dev much easier.

Please note that before running 'make' you must run 'git submodule init' 'git submodule update' and then in JRiftLibrary/OculusSDK run 'cmake .'

### CODE REVIEW

**Comment by StellaArtois** [comment]
Ok, I've modified your pull request to use CMake for the complete
JRiftLibrary build (using jherico's OculusSDK project) and it's running on
Windows currently. Now to test it still works on OSX / Linux, and then I'll
get the pull request updated.

**Comment by feilen** [comment]
Awesome work. I can help test, just let me know what needs done!

**Comment by feilen** [comment]
Couple changes need to be made, I'll work them out and get back to you.

Note for testing, JAVA_HOME needs to be set for FindJNI.cmake to work!

Edit: Tried it out, it built after my changes, but still crashes out with a
SIGSEGV at the moment. Changes I made are up on my repo.

**Comment by StellaArtois** [comment]
Great work, thanks!

I'll get it up and running on the debugger a see what's going on there. I'm
expecting some Minecrift source changes to get the Linux and Mac versions
going anyway to be honest.

**Comment by StellaArtois** [comment]
Could you push your changes to this pull request by the way?

**Comment by feilen** [comment]
Odd, thought I did. Should be up now!

**Comment by feilen** [comment]
Aaah! I got it working! I hadn't been packaging it correctly. But it works!

**Comment by StellaArtois** [comment]
As in you can get Minecrift up and running? Nice one! Which distro?

**Comment by feilen** [comment]
ArchLinux. I'm going to install an Ubuntu virtual machine to compile the upstream .so files, since that's the common 'user friendly' target. I just now added some default optimization options, since by default GCC does no optimization (which is very bad for anything demanding)

**Comment by StellaArtois** [comment]
Great, thank you!

I really need to get myself a Mac so I can build and test on that as well...

**Comment by feilen** [comment]
Hey, if it helps at all, I set up a Mac VM to help port Dolphin to it. It probably can't actually do any 3d rendering, but I can test if it builds or not!

**Comment by feilen** [comment]
Building from Ubuntu doesn't seem to have actually made a difference in the output shared libs, so I'll just build the 32-bit ones on my home arch system.

**Comment by feilen** [comment]
Done! I'm gonna start doing some 'testing' (play for a few hours), I'll let you know if any issues come up. If you don't hear from me again for 24 hours you can assume it's working well.

**Comment by StellaArtois** [comment]
Lol ok! Are all you're latest changes pushed up - if so would like to grab
them. But in your own time, no hurry!

I do have a Mac vm myself so I can look at the builds as well - but like
you I can't run Minecrift up to test it either sadly...

**Comment by feilen** [comment]
Latest changes are all pushed up, as well as binary updates for Linux. 

For Mac, because the Oculus SDK doesn't get built with default optimization options, I'd reccomend configuring CMake like so (with a clean OculusSDK submodule):

```
JAVA_HOME=/path/to/jdk cmake . -DCMAKE_CXX_FLAGS="-O2" -DCMAKE_C_FLAGS="-O2" -DCMAKE_SHARED_LINKER_FLAGS="-Wl,-O1,--sort-common,--as-needed,-z,relro"
```

That'll ensure that libOculusVR.a gets built with the optimization options as well, before being statically linked into libJRift.

**Comment by feilen** [comment]
By the way, on the instructions on mtbs3d, you have the '.exe.txt' and '.jar.txt' for separate versions of the Minecrift installer. But, as with minecraft, you can save the '.exe' version as '.jar' and run it with 'java -jar /path/to/file' and it'll execute cleanly.

**Comment by feilen** [comment]
So it turns out that currently Jherico's fork of the SDK doesn't use -msse2, and CMake uses -O3 instead of -O2 for its release flags (bad, generally slower, less stable). I've created a fix but I'm doing a few more things to adjust the fork to be more like the official SDK, and once that's done it should build much more nicely. (so, basically, hang on just a bit longer while I get this ready the rest of the way)

**Comment by feilen** [comment]
Should be good to go now!

**Comment by StellaArtois** [comment]
Thanks Zach! Hopefully I can get a chance to grab it today and take a look.

**Comment by feilen** [comment]
Playing with use of link-time-optimizations... it's experimental but at this point fairly stable. But the resulting binaries often have greatly reduced size and huge speed increases, since the compiler can see all of the code at once (whereas ordinarily it often can only optimize on a per-function basis). 

Trying it with Minecrift hasn't resulted in any issues so far, so I imagine it's pretty much safe.

**Comment by StellaArtois** [comment]
Thanks Zach. Would you be able to have a quick look at this on OSX (from a
build point-of-view). No probs if not, I'm not going to be able to look at
this for another week or so due to work commitments (damn that real lift
stuff)!

**Comment by StellaArtois** [comment]
Ok, merged this pull request; and then went crazy and merged the 0.3.1 branch into master... finally! Thanks again Zach!

I'd like to put together a couple of scripts to build the cmake and then compile stuff on Linux (or OSX) much like the build_windows.bat file I've already added. What were you calling on the commandline and with what params to build the 32, 64 bit so's and the jnilib?

I'm guessing something along the lines of:

cmake <dir32> CMAKE_FLAGS=-m32
make
cmake <dir64> CMAKE_FLAGS=-m64
make

?

**Pull request merged**
